import type { Region } from "./types";

export const REGIONS: Region[] = [
  {
    id: "moscow",
    name: "Москва",
    geoName: "Москва",
    specializations: ["finance", "tech"],
    gdpIndex: 100,
    population: 10.4,
    unemploymentRate: 6,
    corruptionIndex: 65,
    neighbors: ["moscow_oblast"],
  },
  {
    id: "moscow_oblast",
    name: "Московская область",
    geoName: "Московская область",
    specializations: ["industry", "tech"],
    gdpIndex: 38,
    population: 6.6,
    unemploymentRate: 8,
    corruptionIndex: 68,
    neighbors: ["moscow"],
  },
  {
    id: "spb",
    name: "Санкт-Петербург",
    geoName: "Санкт-Петербург",
    specializations: ["industry", "tech", "ports"],
    gdpIndex: 42,
    population: 4.7,
    unemploymentRate: 7,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "khanty_mansi",
    name: "Ханты-Мансийский АО",
    geoName: "Ханты-Мансийский автономный округ - Югра",
    specializations: ["oil"],
    gdpIndex: 55,
    population: 1.4,
    unemploymentRate: 7,
    corruptionIndex: 58,
    neighbors: ["yamalo_nenets", "sverdlovsk", "krasnoyarsk"],
  },
  {
    id: "yamalo_nenets",
    name: "Ямало-Ненецкий АО",
    geoName: "Ямало-Ненецкий автономный округ",
    specializations: ["gas"],
    gdpIndex: 40,
    population: 0.5,
    unemploymentRate: 6,
    corruptionIndex: 55,
    neighbors: ["khanty_mansi", "krasnoyarsk"],
  },
  {
    id: "sverdlovsk",
    name: "Свердловская область",
    geoName: "Свердловская область",
    specializations: ["metals", "industry"],
    gdpIndex: 33,
    population: 4.5,
    unemploymentRate: 11,
    corruptionIndex: 60,
    neighbors: ["perm", "khanty_mansi", "chelyabinsk", "bashkortostan"],
  },
  {
    id: "tatarstan",
    name: "Республика Татарстан",
    geoName: "Татарстан",
    specializations: ["oil", "industry"],
    gdpIndex: 34,
    population: 3.8,
    unemploymentRate: 9,
    corruptionIndex: 62,
    neighbors: ["bashkortostan", "samara"],
  },
  {
    id: "kemerovo",
    name: "Кемеровская область",
    geoName: "Кемеровская область",
    specializations: ["coal"],
    gdpIndex: 24,
    population: 2.9,
    unemploymentRate: 14,
    corruptionIndex: 63,
    neighbors: ["novosibirsk", "krasnoyarsk"],
  },
  {
    id: "krasnodar",
    name: "Краснодарский край",
    geoName: "Краснодарский край",
    specializations: ["agriculture", "ports"],
    gdpIndex: 32,
    population: 5.1,
    unemploymentRate: 10,
    corruptionIndex: 66,
    neighbors: ["rostov"],
  },
  {
    id: "rostov",
    name: "Ростовская область",
    geoName: "Ростовская область",
    specializations: ["agriculture", "industry"],
    gdpIndex: 24,
    population: 4.4,
    unemploymentRate: 12,
    corruptionIndex: 60,
    neighbors: ["krasnodar", "volgograd"],
  },
  {
    id: "krasnoyarsk",
    name: "Красноярский край",
    geoName: "Красноярский край",
    specializations: ["metals", "industry"],
    gdpIndex: 30,
    population: 3.0,
    unemploymentRate: 11,
    corruptionIndex: 58,
    neighbors: ["yamalo_nenets", "khanty_mansi", "kemerovo", "irkutsk", "sakha"],
  },
  {
    id: "primorye",
    name: "Приморский край",
    geoName: "Приморский край",
    specializations: ["ports"],
    gdpIndex: 16,
    population: 2.1,
    unemploymentRate: 13,
    corruptionIndex: 68,
    neighbors: [],
  },
  {
    id: "bashkortostan",
    name: "Республика Башкортостан",
    geoName: "Башкортостан",
    specializations: ["oil", "industry"],
    gdpIndex: 26,
    population: 4.1,
    unemploymentRate: 10,
    corruptionIndex: 63,
    neighbors: ["tatarstan", "sverdlovsk", "perm", "chelyabinsk"],
  },
  {
    id: "samara",
    name: "Самарская область",
    geoName: "Самарская область",
    specializations: ["industry"],
    gdpIndex: 25,
    population: 3.2,
    unemploymentRate: 10,
    corruptionIndex: 58,
    neighbors: ["tatarstan"],
  },
  {
    id: "nizhny_novgorod",
    name: "Нижегородская область",
    geoName: "Нижегородская область",
    specializations: ["industry"],
    gdpIndex: 23,
    population: 3.6,
    unemploymentRate: 11,
    corruptionIndex: 56,
    neighbors: [],
  },
  {
    id: "chelyabinsk",
    name: "Челябинская область",
    geoName: "Челябинская область",
    specializations: ["metals", "industry"],
    gdpIndex: 22,
    population: 3.6,
    unemploymentRate: 12,
    corruptionIndex: 57,
    neighbors: ["sverdlovsk", "bashkortostan"],
  },
  {
    id: "perm",
    name: "Пермский край",
    geoName: "Пермский край",
    specializations: ["oil", "industry"],
    gdpIndex: 22,
    population: 2.8,
    unemploymentRate: 11,
    corruptionIndex: 55,
    neighbors: ["sverdlovsk", "bashkortostan"],
  },
  {
    id: "irkutsk",
    name: "Иркутская область",
    geoName: "Иркутская область",
    specializations: ["metals", "industry"],
    gdpIndex: 18,
    population: 2.6,
    unemploymentRate: 13,
    corruptionIndex: 60,
    neighbors: ["krasnoyarsk", "sakha"],
  },
  {
    id: "volgograd",
    name: "Волгоградская область",
    geoName: "Волгоградская область",
    specializations: ["industry", "agriculture"],
    gdpIndex: 16,
    population: 2.7,
    unemploymentRate: 12,
    corruptionIndex: 59,
    neighbors: ["rostov"],
  },
  {
    id: "belgorod",
    name: "Белгородская область",
    geoName: "Белгородская область",
    specializations: ["metals", "agriculture"],
    gdpIndex: 14,
    population: 1.5,
    unemploymentRate: 9,
    corruptionIndex: 50,
    neighbors: [],
  },
  {
    id: "lipetsk",
    name: "Липецкая область",
    geoName: "Липецкая область",
    specializations: ["metals"],
    gdpIndex: 11,
    population: 1.2,
    unemploymentRate: 9,
    corruptionIndex: 50,
    neighbors: [],
  },
  {
    id: "murmansk",
    name: "Мурманская область",
    geoName: "Мурманская область",
    specializations: ["metals", "ports"],
    gdpIndex: 12,
    population: 0.9,
    unemploymentRate: 12,
    corruptionIndex: 52,
    neighbors: [],
  },
  {
    id: "sakha",
    name: "Республика Саха (Якутия)",
    geoName: "Республика Саха (Якутия)",
    specializations: ["metals"],
    gdpIndex: 17,
    population: 0.95,
    unemploymentRate: 10,
    corruptionIndex: 60,
    neighbors: ["krasnoyarsk", "irkutsk"],
  },
  {
    id: "novosibirsk",
    name: "Новосибирская область",
    geoName: "Новосибирская область",
    specializations: ["tech", "industry"],
    gdpIndex: 20,
    population: 2.7,
    unemploymentRate: 11,
    corruptionIndex: 54,
    neighbors: ["kemerovo"],
  },

  // Остальные ~59 субъектов РФ — грубее откалиброванные, но правдоподобные
  // оценки относительно соседей (не топ-24 по значимости). neighbors ниже
  // заполняются отдельным проходом по проверенным реальным границам.
  {
    id: "adygea",
    name: "Республика Адыгея",
    geoName: "Адыгея",
    specializations: ["agriculture"],
    gdpIndex: 2,
    population: 0.45,
    unemploymentRate: 14,
    corruptionIndex: 60,
    neighbors: [],
  },
  {
    id: "altai_republic",
    name: "Республика Алтай",
    geoName: "Алтай",
    specializations: ["agriculture"],
    gdpIndex: 1.5,
    population: 0.2,
    unemploymentRate: 18,
    corruptionIndex: 58,
    neighbors: [],
  },
  {
    id: "altai_krai",
    name: "Алтайский край",
    geoName: "Алтайский край",
    specializations: ["agriculture"],
    gdpIndex: 9,
    population: 2.6,
    unemploymentRate: 12,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "amur",
    name: "Амурская область",
    geoName: "Амурская область",
    specializations: ["agriculture"],
    gdpIndex: 6,
    population: 0.9,
    unemploymentRate: 12,
    corruptionIndex: 58,
    neighbors: [],
  },
  {
    id: "arkhangelsk",
    name: "Архангельская область",
    geoName: "Архангельская область",
    specializations: ["industry", "ports"],
    gdpIndex: 11,
    population: 1.4,
    unemploymentRate: 11,
    corruptionIndex: 54,
    neighbors: [],
  },
  {
    id: "astrakhan",
    name: "Астраханская область",
    geoName: "Астраханская область",
    specializations: ["gas", "ports"],
    gdpIndex: 12,
    population: 1.0,
    unemploymentRate: 11,
    corruptionIndex: 57,
    neighbors: [],
  },
  {
    id: "bryansk",
    name: "Брянская область",
    geoName: "Брянская область",
    specializations: ["industry", "agriculture"],
    gdpIndex: 7,
    population: 1.4,
    unemploymentRate: 11,
    corruptionIndex: 53,
    neighbors: [],
  },
  {
    id: "buryatia",
    name: "Республика Бурятия",
    geoName: "Бурятия",
    specializations: ["industry", "agriculture"],
    gdpIndex: 6,
    population: 1.0,
    unemploymentRate: 14,
    corruptionIndex: 58,
    neighbors: [],
  },
  {
    id: "vladimir",
    name: "Владимирская область",
    geoName: "Владимирская область",
    specializations: ["industry"],
    gdpIndex: 10,
    population: 1.5,
    unemploymentRate: 10,
    corruptionIndex: 54,
    neighbors: [],
  },
  {
    id: "vologda",
    name: "Вологодская область",
    geoName: "Вологодская область",
    specializations: ["metals", "industry"],
    gdpIndex: 16,
    population: 1.3,
    unemploymentRate: 9,
    corruptionIndex: 52,
    neighbors: [],
  },
  {
    id: "voronezh",
    name: "Воронежская область",
    geoName: "Воронежская область",
    specializations: ["industry", "agriculture"],
    gdpIndex: 16,
    population: 2.4,
    unemploymentRate: 10,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "dagestan",
    name: "Республика Дагестан",
    geoName: "Дагестан",
    specializations: ["agriculture"],
    gdpIndex: 5,
    population: 2.6,
    unemploymentRate: 22,
    corruptionIndex: 70,
    neighbors: [],
  },
  {
    id: "jewish_ao",
    name: "Еврейская автономная область",
    geoName: "Еврейская автономная область",
    specializations: ["agriculture"],
    gdpIndex: 1.5,
    population: 0.19,
    unemploymentRate: 15,
    corruptionIndex: 60,
    neighbors: [],
  },
  {
    id: "zabaykalsky",
    name: "Забайкальский край",
    geoName: "Забайкальский край",
    specializations: ["metals"],
    gdpIndex: 6,
    population: 1.2,
    unemploymentRate: 14,
    corruptionIndex: 60,
    neighbors: [],
  },
  {
    id: "ivanovo",
    name: "Ивановская область",
    geoName: "Ивановская область",
    specializations: ["industry"],
    gdpIndex: 6,
    population: 1.2,
    unemploymentRate: 13,
    corruptionIndex: 54,
    neighbors: [],
  },
  {
    id: "ingushetia",
    name: "Республика Ингушетия",
    geoName: "Ингушетия",
    specializations: ["agriculture"],
    gdpIndex: 1,
    population: 0.47,
    unemploymentRate: 35,
    corruptionIndex: 72,
    neighbors: [],
  },
  {
    id: "kabardino_balkaria",
    name: "Кабардино-Балкарская Республика",
    geoName: "Кабардино-Балкарская республика",
    specializations: ["agriculture"],
    gdpIndex: 2.5,
    population: 0.9,
    unemploymentRate: 20,
    corruptionIndex: 65,
    neighbors: [],
  },
  {
    id: "kaliningrad",
    name: "Калининградская область",
    geoName: "Калининградская область",
    specializations: ["industry", "ports"],
    gdpIndex: 7,
    population: 0.95,
    unemploymentRate: 11,
    corruptionIndex: 56,
    neighbors: [],
  },
  {
    id: "kaluga",
    name: "Калужская область",
    geoName: "Калужская область",
    specializations: ["industry"],
    gdpIndex: 9,
    population: 1.0,
    unemploymentRate: 10,
    corruptionIndex: 53,
    neighbors: [],
  },
  {
    id: "kamchatka",
    name: "Камчатский край",
    geoName: "Камчатский край",
    specializations: ["ports"],
    gdpIndex: 4,
    population: 0.37,
    unemploymentRate: 13,
    corruptionIndex: 58,
    neighbors: [],
  },
  {
    id: "karachay_cherkessia",
    name: "Карачаево-Черкесская Республика",
    geoName: "Карачаево-Черкесская республика",
    specializations: ["agriculture"],
    gdpIndex: 1.5,
    population: 0.44,
    unemploymentRate: 22,
    corruptionIndex: 64,
    neighbors: [],
  },
  {
    id: "kirov",
    name: "Кировская область",
    geoName: "Кировская область",
    specializations: ["industry"],
    gdpIndex: 7,
    population: 1.5,
    unemploymentRate: 12,
    corruptionIndex: 54,
    neighbors: [],
  },
  {
    id: "kostroma",
    name: "Костромская область",
    geoName: "Костромская область",
    specializations: ["industry"],
    gdpIndex: 6,
    population: 0.75,
    unemploymentRate: 11,
    corruptionIndex: 52,
    neighbors: [],
  },
  {
    id: "kurgan",
    name: "Курганская область",
    geoName: "Курганская область",
    specializations: ["industry"],
    gdpIndex: 5,
    population: 1.05,
    unemploymentRate: 13,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "kursk",
    name: "Курская область",
    geoName: "Курская область",
    specializations: ["metals", "agriculture"],
    gdpIndex: 11,
    population: 1.3,
    unemploymentRate: 10,
    corruptionIndex: 54,
    neighbors: [],
  },
  {
    id: "leningrad_oblast",
    name: "Ленинградская область",
    geoName: "Ленинградская область",
    specializations: ["industry", "ports"],
    gdpIndex: 28,
    population: 1.6,
    unemploymentRate: 8,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "magadan",
    name: "Магаданская область",
    geoName: "Магаданская область",
    specializations: ["metals"],
    gdpIndex: 3,
    population: 0.2,
    unemploymentRate: 15,
    corruptionIndex: 60,
    neighbors: [],
  },
  {
    id: "mari_el",
    name: "Республика Марий Эл",
    geoName: "Марий Эл",
    specializations: ["industry"],
    gdpIndex: 4,
    population: 0.73,
    unemploymentRate: 13,
    corruptionIndex: 56,
    neighbors: [],
  },
  {
    id: "nenets",
    name: "Ненецкий автономный округ",
    geoName: "Ненецкий автономный округ",
    specializations: ["oil"],
    gdpIndex: 9,
    population: 0.042,
    unemploymentRate: 8,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "novgorod",
    name: "Новгородская область",
    geoName: "Новгородская область",
    specializations: ["industry", "agriculture"],
    gdpIndex: 6,
    population: 0.7,
    unemploymentRate: 10,
    corruptionIndex: 52,
    neighbors: [],
  },
  {
    id: "omsk",
    name: "Омская область",
    geoName: "Омская область",
    specializations: ["oil", "industry"],
    gdpIndex: 16,
    population: 2.1,
    unemploymentRate: 11,
    corruptionIndex: 56,
    neighbors: [],
  },
  {
    id: "orenburg",
    name: "Оренбургская область",
    geoName: "Оренбургская область",
    specializations: ["oil", "gas"],
    gdpIndex: 17,
    population: 2.2,
    unemploymentRate: 10,
    corruptionIndex: 57,
    neighbors: [],
  },
  {
    id: "oryol",
    name: "Орловская область",
    geoName: "Орловская область",
    specializations: ["agriculture"],
    gdpIndex: 6,
    population: 0.85,
    unemploymentRate: 11,
    corruptionIndex: 53,
    neighbors: [],
  },
  {
    id: "penza",
    name: "Пензенская область",
    geoName: "Пензенская область",
    specializations: ["industry"],
    gdpIndex: 7,
    population: 1.5,
    unemploymentRate: 11,
    corruptionIndex: 54,
    neighbors: [],
  },
  {
    id: "pskov",
    name: "Псковская область",
    geoName: "Псковская область",
    specializations: ["agriculture"],
    gdpIndex: 5,
    population: 0.78,
    unemploymentRate: 12,
    corruptionIndex: 53,
    neighbors: [],
  },
  {
    id: "kalmykia",
    name: "Республика Калмыкия",
    geoName: "Республика Калмыкия",
    specializations: ["agriculture"],
    gdpIndex: 1.5,
    population: 0.3,
    unemploymentRate: 20,
    corruptionIndex: 62,
    neighbors: [],
  },
  {
    id: "karelia",
    name: "Республика Карелия",
    geoName: "Республика Карелия",
    specializations: ["metals", "industry"],
    gdpIndex: 6,
    population: 0.72,
    unemploymentRate: 12,
    corruptionIndex: 54,
    neighbors: [],
  },
  {
    id: "komi",
    name: "Республика Коми",
    geoName: "Республика Коми",
    specializations: ["oil", "coal"],
    gdpIndex: 18,
    population: 1.1,
    unemploymentRate: 10,
    corruptionIndex: 56,
    neighbors: [],
  },
  {
    id: "mordovia",
    name: "Республика Мордовия",
    geoName: "Республика Мордовия",
    specializations: ["industry"],
    gdpIndex: 5,
    population: 0.9,
    unemploymentRate: 11,
    corruptionIndex: 54,
    neighbors: [],
  },
  {
    id: "khakassia",
    name: "Республика Хакасия",
    geoName: "Республика Хакасия",
    specializations: ["metals"],
    gdpIndex: 10,
    population: 0.58,
    unemploymentRate: 12,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "ryazan",
    name: "Рязанская область",
    geoName: "Рязанская область",
    specializations: ["industry"],
    gdpIndex: 9,
    population: 1.2,
    unemploymentRate: 10,
    corruptionIndex: 53,
    neighbors: [],
  },
  {
    id: "saratov",
    name: "Саратовская область",
    geoName: "Саратовская область",
    specializations: ["gas", "industry"],
    gdpIndex: 15,
    population: 2.7,
    unemploymentRate: 11,
    corruptionIndex: 56,
    neighbors: [],
  },
  {
    id: "sakhalin",
    name: "Сахалинская область",
    geoName: "Сахалинская область",
    specializations: ["oil", "gas", "ports"],
    gdpIndex: 9,
    population: 0.58,
    unemploymentRate: 11,
    corruptionIndex: 58,
    neighbors: [],
  },
  {
    id: "north_ossetia",
    name: "Республика Северная Осетия — Алания",
    geoName: "Северная Осетия - Алания",
    specializations: ["agriculture"],
    gdpIndex: 2.5,
    population: 0.7,
    unemploymentRate: 18,
    corruptionIndex: 62,
    neighbors: [],
  },
  {
    id: "smolensk",
    name: "Смоленская область",
    geoName: "Смоленская область",
    specializations: ["industry"],
    gdpIndex: 7,
    population: 1.0,
    unemploymentRate: 11,
    corruptionIndex: 53,
    neighbors: [],
  },
  {
    id: "stavropol",
    name: "Ставропольский край",
    geoName: "Ставропольский край",
    specializations: ["agriculture"],
    gdpIndex: 15,
    population: 2.7,
    unemploymentRate: 13,
    corruptionIndex: 58,
    neighbors: [],
  },
  {
    id: "tambov",
    name: "Тамбовская область",
    geoName: "Тамбовская область",
    specializations: ["agriculture"],
    gdpIndex: 6,
    population: 1.2,
    unemploymentRate: 11,
    corruptionIndex: 53,
    neighbors: [],
  },
  {
    id: "tver",
    name: "Тверская область",
    geoName: "Тверская область",
    specializations: ["industry"],
    gdpIndex: 9,
    population: 1.5,
    unemploymentRate: 10,
    corruptionIndex: 53,
    neighbors: [],
  },
  {
    id: "tomsk",
    name: "Томская область",
    geoName: "Томская область",
    specializations: ["oil", "tech"],
    gdpIndex: 13,
    population: 1.0,
    unemploymentRate: 10,
    corruptionIndex: 54,
    neighbors: [],
  },
  {
    id: "tula",
    name: "Тульская область",
    geoName: "Тульская область",
    specializations: ["metals", "industry"],
    gdpIndex: 10,
    population: 1.7,
    unemploymentRate: 10,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "tuva",
    name: "Республика Тыва",
    geoName: "Тыва",
    specializations: ["agriculture"],
    gdpIndex: 1.5,
    population: 0.31,
    unemploymentRate: 22,
    corruptionIndex: 62,
    neighbors: [],
  },
  {
    id: "tyumen_south",
    name: "Тюменская область",
    geoName: "Тюменская область",
    specializations: ["oil"],
    gdpIndex: 14,
    population: 1.3,
    unemploymentRate: 9,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "udmurtia",
    name: "Удмуртская Республика",
    geoName: "Удмуртская республика",
    specializations: ["industry"],
    gdpIndex: 13,
    population: 1.6,
    unemploymentRate: 10,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "ulyanovsk",
    name: "Ульяновская область",
    geoName: "Ульяновская область",
    specializations: ["industry"],
    gdpIndex: 11,
    population: 1.4,
    unemploymentRate: 10,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "khabarovsk",
    name: "Хабаровский край",
    geoName: "Хабаровский край",
    specializations: ["industry", "ports"],
    gdpIndex: 14,
    population: 1.5,
    unemploymentRate: 10,
    corruptionIndex: 58,
    neighbors: [],
  },
  {
    id: "chechnya",
    name: "Чеченская Республика",
    geoName: "Чеченская республика",
    specializations: ["oil", "agriculture"],
    gdpIndex: 2,
    population: 1.1,
    unemploymentRate: 30,
    corruptionIndex: 70,
    neighbors: [],
  },
  {
    id: "chuvashia",
    name: "Чувашская Республика",
    geoName: "Чувашия",
    specializations: ["industry"],
    gdpIndex: 6,
    population: 1.3,
    unemploymentRate: 11,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "chukotka",
    name: "Чукотский автономный округ",
    geoName: "Чукотский автономный округ",
    specializations: ["metals"],
    gdpIndex: 2,
    population: 0.06,
    unemploymentRate: 16,
    corruptionIndex: 65,
    neighbors: [],
  },
  {
    id: "yaroslavl",
    name: "Ярославская область",
    geoName: "Ярославская область",
    specializations: ["industry"],
    gdpIndex: 10,
    population: 1.4,
    unemploymentRate: 9,
    corruptionIndex: 53,
    neighbors: [],
  },
];
