import type { Region } from "./types";

type RegionSeed = Omit<Region, "infrastructureLevel">;

const RAW_REGIONS: RegionSeed[] = [
  {
    id: "moscow",
    name: "Москва",
    geoName: "Москва",
    specializations: ["finance", "tech"],
    gdpIndex: 100,
    population: 10.4,
    unemploymentRate: 6,
    corruptionIndex: 65,
    neighbors: ["moscow_oblast"],
  },
  {
    id: "moscow_oblast",
    name: "Московская область",
    geoName: "Московская область",
    specializations: ["industry", "tech"],
    gdpIndex: 38,
    population: 6.6,
    unemploymentRate: 8,
    corruptionIndex: 68,
    neighbors: ["tver", "smolensk", "yaroslavl", "vladimir", "ryazan", "tula", "kaluga", "moscow"],
  },
  {
    id: "spb",
    name: "Санкт-Петербург",
    geoName: "Санкт-Петербург",
    specializations: ["industry", "tech", "ports"],
    gdpIndex: 42,
    population: 4.7,
    unemploymentRate: 7,
    corruptionIndex: 55,
    neighbors: ["leningrad_oblast"],
  },
  {
    id: "khanty_mansi",
    name: "Ханты-Мансийский АО",
    geoName: "Ханты-Мансийский автономный округ - Югра",
    specializations: ["oil"],
    gdpIndex: 55,
    population: 1.4,
    unemploymentRate: 7,
    corruptionIndex: 58,
    neighbors: ["yamalo_nenets", "krasnoyarsk", "tyumen_south", "tomsk", "sverdlovsk", "komi"],
  },
  {
    id: "yamalo_nenets",
    name: "Ямало-Ненецкий АО",
    geoName: "Ямало-Ненецкий автономный округ",
    specializations: ["gas"],
    gdpIndex: 40,
    population: 0.5,
    unemploymentRate: 6,
    corruptionIndex: 55,
    neighbors: ["nenets", "komi", "khanty_mansi", "krasnoyarsk"],
  },
  {
    id: "sverdlovsk",
    name: "Свердловская область",
    geoName: "Свердловская область",
    specializations: ["metals", "industry"],
    gdpIndex: 33,
    population: 4.5,
    unemploymentRate: 11,
    corruptionIndex: 60,
    neighbors: ["perm", "komi", "khanty_mansi", "tyumen_south", "kurgan", "chelyabinsk", "bashkortostan"],
  },
  {
    id: "tatarstan",
    name: "Республика Татарстан",
    geoName: "Татарстан",
    specializations: ["oil", "industry"],
    gdpIndex: 34,
    population: 3.8,
    unemploymentRate: 9,
    corruptionIndex: 62,
    neighbors: ["bashkortostan", "udmurtia", "mari_el", "chuvashia", "kirov", "orenburg", "ulyanovsk", "samara"],
  },
  {
    id: "kemerovo",
    name: "Кемеровская область",
    geoName: "Кемеровская область",
    specializations: ["coal"],
    gdpIndex: 24,
    population: 2.9,
    unemploymentRate: 14,
    corruptionIndex: 63,
    neighbors: ["tomsk", "novosibirsk", "altai_krai", "altai_republic", "krasnoyarsk", "khakassia"],
  },
  {
    id: "krasnodar",
    name: "Краснодарский край",
    geoName: "Краснодарский край",
    specializations: ["agriculture", "ports"],
    gdpIndex: 32,
    population: 5.1,
    unemploymentRate: 10,
    corruptionIndex: 66,
    neighbors: ["rostov", "stavropol", "karachay_cherkessia", "adygea"],
  },
  {
    id: "rostov",
    name: "Ростовская область",
    geoName: "Ростовская область",
    specializations: ["agriculture", "industry"],
    gdpIndex: 24,
    population: 4.4,
    unemploymentRate: 12,
    corruptionIndex: 60,
    neighbors: ["voronezh", "volgograd", "krasnodar", "stavropol", "kalmykia"],
  },
  {
    id: "krasnoyarsk",
    name: "Красноярский край",
    geoName: "Красноярский край",
    specializations: ["metals", "industry"],
    gdpIndex: 30,
    population: 3.0,
    unemploymentRate: 11,
    corruptionIndex: 58,
    neighbors: ["sakha", "irkutsk", "tuva", "khakassia", "kemerovo", "tomsk", "khanty_mansi", "yamalo_nenets"],
  },
  {
    id: "primorye",
    name: "Приморский край",
    geoName: "Приморский край",
    specializations: ["ports"],
    gdpIndex: 16,
    population: 2.1,
    unemploymentRate: 13,
    corruptionIndex: 68,
    neighbors: ["khabarovsk"],
  },
  {
    id: "bashkortostan",
    name: "Республика Башкортостан",
    geoName: "Башкортостан",
    specializations: ["oil", "industry"],
    gdpIndex: 26,
    population: 4.1,
    unemploymentRate: 10,
    corruptionIndex: 63,
    neighbors: ["perm", "sverdlovsk", "chelyabinsk", "orenburg", "tatarstan", "udmurtia"],
  },
  {
    id: "samara",
    name: "Самарская область",
    geoName: "Самарская область",
    specializations: ["industry"],
    gdpIndex: 25,
    population: 3.2,
    unemploymentRate: 10,
    corruptionIndex: 58,
    neighbors: ["saratov", "ulyanovsk", "orenburg", "tatarstan"],
  },
  {
    id: "nizhny_novgorod",
    name: "Нижегородская область",
    geoName: "Нижегородская область",
    specializations: ["industry"],
    gdpIndex: 23,
    population: 3.6,
    unemploymentRate: 11,
    corruptionIndex: 56,
    neighbors: ["kostroma", "kirov", "mari_el", "chuvashia", "mordovia", "ryazan", "vladimir", "ivanovo"],
  },
  {
    id: "chelyabinsk",
    name: "Челябинская область",
    geoName: "Челябинская область",
    specializations: ["metals", "industry"],
    gdpIndex: 22,
    population: 3.6,
    unemploymentRate: 12,
    corruptionIndex: 57,
    neighbors: ["sverdlovsk", "kurgan", "orenburg", "bashkortostan"],
  },
  {
    id: "perm",
    name: "Пермский край",
    geoName: "Пермский край",
    specializations: ["oil", "industry"],
    gdpIndex: 22,
    population: 2.8,
    unemploymentRate: 11,
    corruptionIndex: 55,
    neighbors: ["komi", "kirov", "udmurtia", "bashkortostan", "sverdlovsk"],
  },
  {
    id: "irkutsk",
    name: "Иркутская область",
    geoName: "Иркутская область",
    specializations: ["metals", "industry"],
    gdpIndex: 18,
    population: 2.6,
    unemploymentRate: 13,
    corruptionIndex: 60,
    neighbors: ["krasnoyarsk", "sakha", "zabaykalsky", "buryatia", "tuva"],
  },
  {
    id: "volgograd",
    name: "Волгоградская область",
    geoName: "Волгоградская область",
    specializations: ["industry", "agriculture"],
    gdpIndex: 16,
    population: 2.7,
    unemploymentRate: 12,
    corruptionIndex: 59,
    neighbors: ["saratov", "voronezh", "rostov", "astrakhan", "kalmykia"],
  },
  {
    id: "belgorod",
    name: "Белгородская область",
    geoName: "Белгородская область",
    specializations: ["metals", "agriculture"],
    gdpIndex: 14,
    population: 1.5,
    unemploymentRate: 9,
    corruptionIndex: 50,
    neighbors: ["kursk", "voronezh"],
  },
  {
    id: "lipetsk",
    name: "Липецкая область",
    geoName: "Липецкая область",
    specializations: ["metals"],
    gdpIndex: 11,
    population: 1.2,
    unemploymentRate: 9,
    corruptionIndex: 50,
    neighbors: ["kursk", "oryol", "tula", "ryazan", "tambov", "voronezh"],
  },
  {
    id: "murmansk",
    name: "Мурманская область",
    geoName: "Мурманская область",
    specializations: ["metals", "ports"],
    gdpIndex: 12,
    population: 0.9,
    unemploymentRate: 12,
    corruptionIndex: 52,
    neighbors: ["karelia", "arkhangelsk"],
  },
  {
    id: "sakha",
    name: "Республика Саха (Якутия)",
    geoName: "Республика Саха (Якутия)",
    specializations: ["metals"],
    gdpIndex: 17,
    population: 0.95,
    unemploymentRate: 10,
    corruptionIndex: 60,
    neighbors: ["krasnoyarsk", "irkutsk", "amur", "zabaykalsky", "khabarovsk", "magadan", "chukotka"],
  },
  {
    id: "novosibirsk",
    name: "Новосибирская область",
    geoName: "Новосибирская область",
    specializations: ["tech", "industry"],
    gdpIndex: 20,
    population: 2.7,
    unemploymentRate: 11,
    corruptionIndex: 54,
    neighbors: ["tomsk", "omsk", "altai_krai", "kemerovo"],
  },

  // Остальные ~59 субъектов РФ — грубее откалиброванные, но правдоподобные
  // оценки относительно соседей (не топ-24 по значимости). neighbors ниже
  // заполняются отдельным проходом по проверенным реальным границам.
  {
    id: "adygea",
    name: "Республика Адыгея",
    geoName: "Адыгея",
    specializations: ["agriculture"],
    gdpIndex: 2,
    population: 0.45,
    unemploymentRate: 14,
    corruptionIndex: 60,
    neighbors: ["krasnodar"],
  },
  {
    id: "altai_republic",
    name: "Республика Алтай",
    geoName: "Алтай",
    specializations: ["agriculture"],
    gdpIndex: 1.5,
    population: 0.2,
    unemploymentRate: 18,
    corruptionIndex: 58,
    neighbors: ["altai_krai", "kemerovo", "khakassia", "tuva"],
  },
  {
    id: "altai_krai",
    name: "Алтайский край",
    geoName: "Алтайский край",
    specializations: ["agriculture"],
    gdpIndex: 9,
    population: 2.6,
    unemploymentRate: 12,
    corruptionIndex: 55,
    neighbors: ["novosibirsk", "kemerovo", "altai_republic"],
  },
  {
    id: "amur",
    name: "Амурская область",
    geoName: "Амурская область",
    specializations: ["agriculture"],
    gdpIndex: 6,
    population: 0.9,
    unemploymentRate: 12,
    corruptionIndex: 58,
    neighbors: ["sakha", "khabarovsk", "jewish_ao", "zabaykalsky"],
  },
  {
    id: "arkhangelsk",
    name: "Архангельская область",
    geoName: "Архангельская область",
    specializations: ["industry", "ports"],
    gdpIndex: 11,
    population: 1.4,
    unemploymentRate: 11,
    corruptionIndex: 54,
    neighbors: ["karelia", "murmansk", "vologda", "kirov", "nenets", "komi"],
  },
  {
    id: "astrakhan",
    name: "Астраханская область",
    geoName: "Астраханская область",
    specializations: ["gas", "ports"],
    gdpIndex: 12,
    population: 1.0,
    unemploymentRate: 11,
    corruptionIndex: 57,
    neighbors: ["volgograd", "kalmykia"],
  },
  {
    id: "bryansk",
    name: "Брянская область",
    geoName: "Брянская область",
    specializations: ["industry", "agriculture"],
    gdpIndex: 7,
    population: 1.4,
    unemploymentRate: 11,
    corruptionIndex: 53,
    neighbors: ["smolensk", "kaluga", "oryol", "kursk"],
  },
  {
    id: "buryatia",
    name: "Республика Бурятия",
    geoName: "Бурятия",
    specializations: ["industry", "agriculture"],
    gdpIndex: 6,
    population: 1.0,
    unemploymentRate: 14,
    corruptionIndex: 58,
    neighbors: ["irkutsk", "zabaykalsky", "tuva"],
  },
  {
    id: "vladimir",
    name: "Владимирская область",
    geoName: "Владимирская область",
    specializations: ["industry"],
    gdpIndex: 10,
    population: 1.5,
    unemploymentRate: 10,
    corruptionIndex: 54,
    neighbors: ["moscow_oblast", "ryazan", "nizhny_novgorod", "ivanovo", "yaroslavl"],
  },
  {
    id: "vologda",
    name: "Вологодская область",
    geoName: "Вологодская область",
    specializations: ["metals", "industry"],
    gdpIndex: 16,
    population: 1.3,
    unemploymentRate: 9,
    corruptionIndex: 52,
    neighbors: ["arkhangelsk", "kirov", "kostroma", "yaroslavl", "tver", "novgorod", "leningrad_oblast", "karelia"],
  },
  {
    id: "voronezh",
    name: "Воронежская область",
    geoName: "Воронежская область",
    specializations: ["industry", "agriculture"],
    gdpIndex: 16,
    population: 2.4,
    unemploymentRate: 10,
    corruptionIndex: 55,
    neighbors: ["belgorod", "kursk", "lipetsk", "tambov", "saratov", "volgograd", "rostov"],
  },
  {
    id: "dagestan",
    name: "Республика Дагестан",
    geoName: "Дагестан",
    specializations: ["agriculture"],
    gdpIndex: 5,
    population: 2.6,
    unemploymentRate: 22,
    corruptionIndex: 70,
    neighbors: ["chechnya", "stavropol", "kalmykia"],
  },
  {
    id: "jewish_ao",
    name: "Еврейская автономная область",
    geoName: "Еврейская автономная область",
    specializations: ["agriculture"],
    gdpIndex: 1.5,
    population: 0.19,
    unemploymentRate: 15,
    corruptionIndex: 60,
    neighbors: ["amur", "khabarovsk"],
  },
  {
    id: "zabaykalsky",
    name: "Забайкальский край",
    geoName: "Забайкальский край",
    specializations: ["metals"],
    gdpIndex: 6,
    population: 1.2,
    unemploymentRate: 14,
    corruptionIndex: 60,
    neighbors: ["amur", "irkutsk", "buryatia", "sakha"],
  },
  {
    id: "ivanovo",
    name: "Ивановская область",
    geoName: "Ивановская область",
    specializations: ["industry"],
    gdpIndex: 6,
    population: 1.2,
    unemploymentRate: 13,
    corruptionIndex: 54,
    neighbors: ["vladimir", "yaroslavl", "nizhny_novgorod", "kostroma"],
  },
  {
    id: "ingushetia",
    name: "Республика Ингушетия",
    geoName: "Ингушетия",
    specializations: ["agriculture"],
    gdpIndex: 1,
    population: 0.47,
    unemploymentRate: 35,
    corruptionIndex: 72,
    neighbors: ["north_ossetia", "chechnya"],
  },
  {
    id: "kabardino_balkaria",
    name: "Кабардино-Балкарская Республика",
    geoName: "Кабардино-Балкарская республика",
    specializations: ["agriculture"],
    gdpIndex: 2.5,
    population: 0.9,
    unemploymentRate: 20,
    corruptionIndex: 65,
    neighbors: ["stavropol", "karachay_cherkessia", "north_ossetia"],
  },
  {
    id: "kaliningrad",
    name: "Калининградская область",
    geoName: "Калининградская область",
    specializations: ["industry", "ports"],
    gdpIndex: 7,
    population: 0.95,
    unemploymentRate: 11,
    corruptionIndex: 56,
    neighbors: [],
  },
  {
    id: "kaluga",
    name: "Калужская область",
    geoName: "Калужская область",
    specializations: ["industry"],
    gdpIndex: 9,
    population: 1.0,
    unemploymentRate: 10,
    corruptionIndex: 53,
    neighbors: ["moscow_oblast", "tula", "bryansk", "smolensk", "oryol"],
  },
  {
    id: "kamchatka",
    name: "Камчатский край",
    geoName: "Камчатский край",
    specializations: ["ports"],
    gdpIndex: 4,
    population: 0.37,
    unemploymentRate: 13,
    corruptionIndex: 58,
    neighbors: ["chukotka", "magadan"],
  },
  {
    id: "karachay_cherkessia",
    name: "Карачаево-Черкесская Республика",
    geoName: "Карачаево-Черкесская республика",
    specializations: ["agriculture"],
    gdpIndex: 1.5,
    population: 0.44,
    unemploymentRate: 22,
    corruptionIndex: 64,
    neighbors: ["krasnodar", "stavropol", "kabardino_balkaria"],
  },
  {
    id: "kirov",
    name: "Кировская область",
    geoName: "Кировская область",
    specializations: ["industry"],
    gdpIndex: 7,
    population: 1.5,
    unemploymentRate: 12,
    corruptionIndex: 54,
    neighbors: ["perm", "udmurtia", "komi", "arkhangelsk", "vologda", "kostroma", "nizhny_novgorod", "mari_el", "tatarstan"],
  },
  {
    id: "kostroma",
    name: "Костромская область",
    geoName: "Костромская область",
    specializations: ["industry"],
    gdpIndex: 6,
    population: 0.75,
    unemploymentRate: 11,
    corruptionIndex: 52,
    neighbors: ["ivanovo", "yaroslavl", "vologda", "kirov", "nizhny_novgorod"],
  },
  {
    id: "kurgan",
    name: "Курганская область",
    geoName: "Курганская область",
    specializations: ["industry"],
    gdpIndex: 5,
    population: 1.05,
    unemploymentRate: 13,
    corruptionIndex: 55,
    neighbors: ["chelyabinsk", "sverdlovsk", "tyumen_south"],
  },
  {
    id: "kursk",
    name: "Курская область",
    geoName: "Курская область",
    specializations: ["metals", "agriculture"],
    gdpIndex: 11,
    population: 1.3,
    unemploymentRate: 10,
    corruptionIndex: 54,
    neighbors: ["bryansk", "oryol", "lipetsk", "voronezh", "belgorod"],
  },
  {
    id: "leningrad_oblast",
    name: "Ленинградская область",
    geoName: "Ленинградская область",
    specializations: ["industry", "ports"],
    gdpIndex: 28,
    population: 1.6,
    unemploymentRate: 8,
    corruptionIndex: 55,
    neighbors: ["spb", "novgorod", "pskov", "vologda", "karelia"],
  },
  {
    id: "magadan",
    name: "Магаданская область",
    geoName: "Магаданская область",
    specializations: ["metals"],
    gdpIndex: 3,
    population: 0.2,
    unemploymentRate: 15,
    corruptionIndex: 60,
    neighbors: ["sakha", "chukotka", "kamchatka", "khabarovsk"],
  },
  {
    id: "mari_el",
    name: "Республика Марий Эл",
    geoName: "Марий Эл",
    specializations: ["industry"],
    gdpIndex: 4,
    population: 0.73,
    unemploymentRate: 13,
    corruptionIndex: 56,
    neighbors: ["kirov", "nizhny_novgorod", "chuvashia", "tatarstan"],
  },
  {
    id: "nenets",
    name: "Ненецкий автономный округ",
    geoName: "Ненецкий автономный округ",
    specializations: ["oil"],
    gdpIndex: 9,
    population: 0.042,
    unemploymentRate: 8,
    corruptionIndex: 55,
    neighbors: ["komi", "arkhangelsk", "yamalo_nenets"],
  },
  {
    id: "novgorod",
    name: "Новгородская область",
    geoName: "Новгородская область",
    specializations: ["industry", "agriculture"],
    gdpIndex: 6,
    population: 0.7,
    unemploymentRate: 10,
    corruptionIndex: 52,
    neighbors: ["pskov", "tver", "leningrad_oblast", "vologda"],
  },
  {
    id: "omsk",
    name: "Омская область",
    geoName: "Омская область",
    specializations: ["oil", "industry"],
    gdpIndex: 16,
    population: 2.1,
    unemploymentRate: 11,
    corruptionIndex: 56,
    neighbors: ["tyumen_south", "novosibirsk", "tomsk"],
  },
  {
    id: "orenburg",
    name: "Оренбургская область",
    geoName: "Оренбургская область",
    specializations: ["oil", "gas"],
    gdpIndex: 17,
    population: 2.2,
    unemploymentRate: 10,
    corruptionIndex: 57,
    neighbors: ["samara", "tatarstan", "bashkortostan", "chelyabinsk"],
  },
  {
    id: "oryol",
    name: "Орловская область",
    geoName: "Орловская область",
    specializations: ["agriculture"],
    gdpIndex: 6,
    population: 0.85,
    unemploymentRate: 11,
    corruptionIndex: 53,
    neighbors: ["kursk", "bryansk", "kaluga", "tula", "lipetsk"],
  },
  {
    id: "penza",
    name: "Пензенская область",
    geoName: "Пензенская область",
    specializations: ["industry"],
    gdpIndex: 7,
    population: 1.5,
    unemploymentRate: 11,
    corruptionIndex: 54,
    neighbors: ["saratov", "tambov", "ulyanovsk", "mordovia", "ryazan"],
  },
  {
    id: "pskov",
    name: "Псковская область",
    geoName: "Псковская область",
    specializations: ["agriculture"],
    gdpIndex: 5,
    population: 0.78,
    unemploymentRate: 12,
    corruptionIndex: 53,
    neighbors: ["leningrad_oblast", "novgorod", "tver", "smolensk"],
  },
  {
    id: "kalmykia",
    name: "Республика Калмыкия",
    geoName: "Республика Калмыкия",
    specializations: ["agriculture"],
    gdpIndex: 1.5,
    population: 0.3,
    unemploymentRate: 20,
    corruptionIndex: 62,
    neighbors: ["stavropol", "dagestan", "volgograd", "astrakhan", "rostov"],
  },
  {
    id: "karelia",
    name: "Республика Карелия",
    geoName: "Республика Карелия",
    specializations: ["metals", "industry"],
    gdpIndex: 6,
    population: 0.72,
    unemploymentRate: 12,
    corruptionIndex: 54,
    neighbors: ["leningrad_oblast", "vologda", "murmansk", "arkhangelsk"],
  },
  {
    id: "komi",
    name: "Республика Коми",
    geoName: "Республика Коми",
    specializations: ["oil", "coal"],
    gdpIndex: 18,
    population: 1.1,
    unemploymentRate: 10,
    corruptionIndex: 56,
    neighbors: ["nenets", "arkhangelsk", "kirov", "perm", "sverdlovsk", "yamalo_nenets", "khanty_mansi"],
  },
  {
    id: "mordovia",
    name: "Республика Мордовия",
    geoName: "Республика Мордовия",
    specializations: ["industry"],
    gdpIndex: 5,
    population: 0.9,
    unemploymentRate: 11,
    corruptionIndex: 54,
    neighbors: ["ulyanovsk", "penza", "ryazan", "nizhny_novgorod", "chuvashia"],
  },
  {
    id: "khakassia",
    name: "Республика Хакасия",
    geoName: "Республика Хакасия",
    specializations: ["metals"],
    gdpIndex: 10,
    population: 0.58,
    unemploymentRate: 12,
    corruptionIndex: 55,
    neighbors: ["krasnoyarsk", "tuva", "altai_republic", "kemerovo"],
  },
  {
    id: "ryazan",
    name: "Рязанская область",
    geoName: "Рязанская область",
    specializations: ["industry"],
    gdpIndex: 9,
    population: 1.2,
    unemploymentRate: 10,
    corruptionIndex: 53,
    neighbors: ["vladimir", "nizhny_novgorod", "mordovia", "penza", "tambov", "lipetsk", "tula", "moscow_oblast"],
  },
  {
    id: "saratov",
    name: "Саратовская область",
    geoName: "Саратовская область",
    specializations: ["gas", "industry"],
    gdpIndex: 15,
    population: 2.7,
    unemploymentRate: 11,
    corruptionIndex: 56,
    neighbors: ["samara", "ulyanovsk", "penza", "voronezh", "tambov", "volgograd"],
  },
  {
    id: "sakhalin",
    name: "Сахалинская область",
    geoName: "Сахалинская область",
    specializations: ["oil", "gas", "ports"],
    gdpIndex: 9,
    population: 0.58,
    unemploymentRate: 11,
    corruptionIndex: 58,
    neighbors: [],
  },
  {
    id: "north_ossetia",
    name: "Республика Северная Осетия — Алания",
    geoName: "Северная Осетия - Алания",
    specializations: ["agriculture"],
    gdpIndex: 2.5,
    population: 0.7,
    unemploymentRate: 18,
    corruptionIndex: 62,
    neighbors: ["kabardino_balkaria", "stavropol", "ingushetia", "chechnya"],
  },
  {
    id: "smolensk",
    name: "Смоленская область",
    geoName: "Смоленская область",
    specializations: ["industry"],
    gdpIndex: 7,
    population: 1.0,
    unemploymentRate: 11,
    corruptionIndex: 53,
    neighbors: ["pskov", "tver", "moscow_oblast", "kaluga", "bryansk"],
  },
  {
    id: "stavropol",
    name: "Ставропольский край",
    geoName: "Ставропольский край",
    specializations: ["agriculture"],
    gdpIndex: 15,
    population: 2.7,
    unemploymentRate: 13,
    corruptionIndex: 58,
    neighbors: ["dagestan", "kabardino_balkaria", "kalmykia", "karachay_cherkessia", "north_ossetia", "chechnya", "krasnodar", "rostov"],
  },
  {
    id: "tambov",
    name: "Тамбовская область",
    geoName: "Тамбовская область",
    specializations: ["agriculture"],
    gdpIndex: 6,
    population: 1.2,
    unemploymentRate: 11,
    corruptionIndex: 53,
    neighbors: ["ryazan", "penza", "saratov", "voronezh", "lipetsk"],
  },
  {
    id: "tver",
    name: "Тверская область",
    geoName: "Тверская область",
    specializations: ["industry"],
    gdpIndex: 9,
    population: 1.5,
    unemploymentRate: 10,
    corruptionIndex: 53,
    neighbors: ["moscow_oblast", "yaroslavl", "vologda", "novgorod", "smolensk", "pskov"],
  },
  {
    id: "tomsk",
    name: "Томская область",
    geoName: "Томская область",
    specializations: ["oil", "tech"],
    gdpIndex: 13,
    population: 1.0,
    unemploymentRate: 10,
    corruptionIndex: 54,
    neighbors: ["omsk", "tyumen_south", "khanty_mansi", "krasnoyarsk", "kemerovo", "novosibirsk"],
  },
  {
    id: "tula",
    name: "Тульская область",
    geoName: "Тульская область",
    specializations: ["metals", "industry"],
    gdpIndex: 10,
    population: 1.7,
    unemploymentRate: 10,
    corruptionIndex: 55,
    neighbors: ["oryol", "kaluga", "moscow_oblast", "ryazan", "lipetsk"],
  },
  {
    id: "tuva",
    name: "Республика Тыва",
    geoName: "Тыва",
    specializations: ["agriculture"],
    gdpIndex: 1.5,
    population: 0.31,
    unemploymentRate: 22,
    corruptionIndex: 62,
    neighbors: ["buryatia", "irkutsk", "krasnoyarsk", "khakassia", "altai_republic"],
  },
  {
    id: "tyumen_south",
    name: "Тюменская область",
    geoName: "Тюменская область",
    specializations: ["oil"],
    gdpIndex: 14,
    population: 1.3,
    unemploymentRate: 9,
    corruptionIndex: 55,
    neighbors: ["sverdlovsk", "kurgan", "omsk", "tomsk", "khanty_mansi"],
  },
  {
    id: "udmurtia",
    name: "Удмуртская Республика",
    geoName: "Удмуртская республика",
    specializations: ["industry"],
    gdpIndex: 13,
    population: 1.6,
    unemploymentRate: 10,
    corruptionIndex: 55,
    neighbors: ["kirov", "perm", "bashkortostan", "tatarstan"],
  },
  {
    id: "ulyanovsk",
    name: "Ульяновская область",
    geoName: "Ульяновская область",
    specializations: ["industry"],
    gdpIndex: 11,
    population: 1.4,
    unemploymentRate: 10,
    corruptionIndex: 55,
    neighbors: ["samara", "saratov", "penza", "mordovia", "chuvashia", "tatarstan"],
  },
  {
    id: "khabarovsk",
    name: "Хабаровский край",
    geoName: "Хабаровский край",
    specializations: ["industry", "ports"],
    gdpIndex: 14,
    population: 1.5,
    unemploymentRate: 10,
    corruptionIndex: 58,
    neighbors: ["primorye", "jewish_ao", "sakha", "magadan", "amur"],
  },
  {
    id: "chechnya",
    name: "Чеченская Республика",
    geoName: "Чеченская республика",
    specializations: ["oil", "agriculture"],
    gdpIndex: 2,
    population: 1.1,
    unemploymentRate: 30,
    corruptionIndex: 70,
    neighbors: ["dagestan", "ingushetia", "north_ossetia", "stavropol"],
  },
  {
    id: "chuvashia",
    name: "Чувашская Республика",
    geoName: "Чувашия",
    specializations: ["industry"],
    gdpIndex: 6,
    population: 1.3,
    unemploymentRate: 11,
    corruptionIndex: 55,
    neighbors: ["nizhny_novgorod", "mordovia", "ulyanovsk", "tatarstan", "mari_el"],
  },
  {
    id: "chukotka",
    name: "Чукотский автономный округ",
    geoName: "Чукотский автономный округ",
    specializations: ["metals"],
    gdpIndex: 2,
    population: 0.06,
    unemploymentRate: 16,
    corruptionIndex: 65,
    neighbors: ["sakha", "magadan", "kamchatka"],
  },
  {
    id: "yaroslavl",
    name: "Ярославская область",
    geoName: "Ярославская область",
    specializations: ["industry"],
    gdpIndex: 10,
    population: 1.4,
    unemploymentRate: 9,
    corruptionIndex: 53,
    neighbors: ["vologda", "moscow_oblast", "vladimir", "tver", "kostroma", "ivanovo"],
  },
];

// Инфраструктура — статический сид-показатель, выведенный один раз из
// стартового gdpIndex региона (не вбит вручную для всех 83 регионов и не
// пересчитывается по ходу игры — см. план "Точные цифры..."). Более
// развитый по стартовому ВВП регион считается изначально лучше
// обустроенным инфраструктурно.
const gdpIndexValues = RAW_REGIONS.map((r) => r.gdpIndex);
const minGdpIndex = Math.min(...gdpIndexValues);
const maxGdpIndex = Math.max(...gdpIndexValues);

function deriveInfrastructureLevel(gdpIndex: number): number {
  const t = (gdpIndex - minGdpIndex) / (maxGdpIndex - minGdpIndex);
  return 15 + t * (95 - 15);
}

export const REGIONS: Region[] = RAW_REGIONS.map((r) => ({
  ...r,
  infrastructureLevel: deriveInfrastructureLevel(r.gdpIndex),
}));

export const REGIONS_BY_ID: Map<string, Region> = new Map(
  REGIONS.map((r) => [r.id, r]),
);
