import type { Region } from "./types";

export const REGIONS: Region[] = [
  {
    id: "moscow",
    name: "Москва",
    geoName: "Москва",
    specializations: ["finance", "tech"],
    gdpIndex: 100,
    population: 10.4,
    unemploymentRate: 6,
    corruptionIndex: 65,
    neighbors: ["moscow_oblast"],
  },
  {
    id: "moscow_oblast",
    name: "Московская область",
    geoName: "Московская область",
    specializations: ["industry", "tech"],
    gdpIndex: 38,
    population: 6.6,
    unemploymentRate: 8,
    corruptionIndex: 68,
    neighbors: ["moscow"],
  },
  {
    id: "spb",
    name: "Санкт-Петербург",
    geoName: "Санкт-Петербург",
    specializations: ["industry", "tech", "ports"],
    gdpIndex: 42,
    population: 4.7,
    unemploymentRate: 7,
    corruptionIndex: 55,
    neighbors: [],
  },
  {
    id: "khanty_mansi",
    name: "Ханты-Мансийский АО",
    geoName: "Ханты-Мансийский автономный округ - Югра",
    specializations: ["oil"],
    gdpIndex: 55,
    population: 1.4,
    unemploymentRate: 7,
    corruptionIndex: 58,
    neighbors: ["yamalo_nenets", "sverdlovsk", "krasnoyarsk"],
  },
  {
    id: "yamalo_nenets",
    name: "Ямало-Ненецкий АО",
    geoName: "Ямало-Ненецкий автономный округ",
    specializations: ["gas"],
    gdpIndex: 40,
    population: 0.5,
    unemploymentRate: 6,
    corruptionIndex: 55,
    neighbors: ["khanty_mansi", "krasnoyarsk"],
  },
  {
    id: "sverdlovsk",
    name: "Свердловская область",
    geoName: "Свердловская область",
    specializations: ["metals", "industry"],
    gdpIndex: 33,
    population: 4.5,
    unemploymentRate: 11,
    corruptionIndex: 60,
    neighbors: ["perm", "khanty_mansi", "chelyabinsk", "bashkortostan"],
  },
  {
    id: "tatarstan",
    name: "Республика Татарстан",
    geoName: "Татарстан",
    specializations: ["oil", "industry"],
    gdpIndex: 34,
    population: 3.8,
    unemploymentRate: 9,
    corruptionIndex: 62,
    neighbors: ["bashkortostan", "samara"],
  },
  {
    id: "kemerovo",
    name: "Кемеровская область",
    geoName: "Кемеровская область",
    specializations: ["coal"],
    gdpIndex: 24,
    population: 2.9,
    unemploymentRate: 14,
    corruptionIndex: 63,
    neighbors: ["novosibirsk", "krasnoyarsk"],
  },
  {
    id: "krasnodar",
    name: "Краснодарский край",
    geoName: "Краснодарский край",
    specializations: ["agriculture", "ports"],
    gdpIndex: 32,
    population: 5.1,
    unemploymentRate: 10,
    corruptionIndex: 66,
    neighbors: ["rostov"],
  },
  {
    id: "rostov",
    name: "Ростовская область",
    geoName: "Ростовская область",
    specializations: ["agriculture", "industry"],
    gdpIndex: 24,
    population: 4.4,
    unemploymentRate: 12,
    corruptionIndex: 60,
    neighbors: ["krasnodar", "volgograd"],
  },
  {
    id: "krasnoyarsk",
    name: "Красноярский край",
    geoName: "Красноярский край",
    specializations: ["metals", "industry"],
    gdpIndex: 30,
    population: 3.0,
    unemploymentRate: 11,
    corruptionIndex: 58,
    neighbors: ["yamalo_nenets", "khanty_mansi", "kemerovo", "irkutsk", "sakha"],
  },
  {
    id: "primorye",
    name: "Приморский край",
    geoName: "Приморский край",
    specializations: ["ports"],
    gdpIndex: 16,
    population: 2.1,
    unemploymentRate: 13,
    corruptionIndex: 68,
    neighbors: [],
  },
  {
    id: "bashkortostan",
    name: "Республика Башкортостан",
    geoName: "Башкортостан",
    specializations: ["oil", "industry"],
    gdpIndex: 26,
    population: 4.1,
    unemploymentRate: 10,
    corruptionIndex: 63,
    neighbors: ["tatarstan", "sverdlovsk", "perm", "chelyabinsk"],
  },
  {
    id: "samara",
    name: "Самарская область",
    geoName: "Самарская область",
    specializations: ["industry"],
    gdpIndex: 25,
    population: 3.2,
    unemploymentRate: 10,
    corruptionIndex: 58,
    neighbors: ["tatarstan"],
  },
  {
    id: "nizhny_novgorod",
    name: "Нижегородская область",
    geoName: "Нижегородская область",
    specializations: ["industry"],
    gdpIndex: 23,
    population: 3.6,
    unemploymentRate: 11,
    corruptionIndex: 56,
    neighbors: [],
  },
  {
    id: "chelyabinsk",
    name: "Челябинская область",
    geoName: "Челябинская область",
    specializations: ["metals", "industry"],
    gdpIndex: 22,
    population: 3.6,
    unemploymentRate: 12,
    corruptionIndex: 57,
    neighbors: ["sverdlovsk", "bashkortostan"],
  },
  {
    id: "perm",
    name: "Пермский край",
    geoName: "Пермский край",
    specializations: ["oil", "industry"],
    gdpIndex: 22,
    population: 2.8,
    unemploymentRate: 11,
    corruptionIndex: 55,
    neighbors: ["sverdlovsk", "bashkortostan"],
  },
  {
    id: "irkutsk",
    name: "Иркутская область",
    geoName: "Иркутская область",
    specializations: ["metals", "industry"],
    gdpIndex: 18,
    population: 2.6,
    unemploymentRate: 13,
    corruptionIndex: 60,
    neighbors: ["krasnoyarsk", "sakha"],
  },
  {
    id: "volgograd",
    name: "Волгоградская область",
    geoName: "Волгоградская область",
    specializations: ["industry", "agriculture"],
    gdpIndex: 16,
    population: 2.7,
    unemploymentRate: 12,
    corruptionIndex: 59,
    neighbors: ["rostov"],
  },
  {
    id: "belgorod",
    name: "Белгородская область",
    geoName: "Белгородская область",
    specializations: ["metals", "agriculture"],
    gdpIndex: 14,
    population: 1.5,
    unemploymentRate: 9,
    corruptionIndex: 50,
    neighbors: [],
  },
  {
    id: "lipetsk",
    name: "Липецкая область",
    geoName: "Липецкая область",
    specializations: ["metals"],
    gdpIndex: 11,
    population: 1.2,
    unemploymentRate: 9,
    corruptionIndex: 50,
    neighbors: [],
  },
  {
    id: "murmansk",
    name: "Мурманская область",
    geoName: "Мурманская область",
    specializations: ["metals", "ports"],
    gdpIndex: 12,
    population: 0.9,
    unemploymentRate: 12,
    corruptionIndex: 52,
    neighbors: [],
  },
  {
    id: "sakha",
    name: "Республика Саха (Якутия)",
    geoName: "Республика Саха (Якутия)",
    specializations: ["metals"],
    gdpIndex: 17,
    population: 0.95,
    unemploymentRate: 10,
    corruptionIndex: 60,
    neighbors: ["krasnoyarsk", "irkutsk"],
  },
  {
    id: "novosibirsk",
    name: "Новосибирская область",
    geoName: "Новосибирская область",
    specializations: ["tech", "industry"],
    gdpIndex: 20,
    population: 2.7,
    unemploymentRate: 11,
    corruptionIndex: 54,
    neighbors: ["kemerovo"],
  },
];
